import { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Sparkles, Dumbbell, Apple, ChevronRight, Play } from "lucide-react";

interface OnboardingProps {
  onFinish: () => void;
}

export default function OnboardingView({ onFinish }: OnboardingProps) {
  const [step, setStep] = useState(1);

  const screens = [
    {
      id: 1,
      title: "Welcome to FitGen AI",
      subtitle: "Your AI-powered personal fitness coach.",
      description: "Get hyper-personalized training routines and customized meal guides structured by state-of-the-art AI.",
      icon: <Sparkles className="w-16 h-16 text-emerald-400" />,
      gradient: "from-teal-900 via-emerald-950 to-slate-950",
      accent: "text-emerald-400"
    },
    {
      id: 2,
      title: "Personalized Workouts",
      subtitle: "Receive workout plans based on your goals and fitness level.",
      description: "Adaptive routines designed around your available equipment—whether you are training at home or at a fully equipped commercial gym.",
      icon: <Dumbbell className="w-16 h-16 text-sky-400" />,
      gradient: "from-sky-950 via-slate-950 to-emerald-950",
      accent: "text-sky-400"
    },
    {
      id: 3,
      title: "Healthy Nutrition",
      subtitle: "Get meal plans and calorie recommendations generated by AI.",
      description: "Delicious recipes catered to your cuisine preferences, grocery budget, and allergies, combined with automatic macro tracking.",
      icon: <Apple className="w-16 h-16 text-lime-400" />,
      gradient: "from-emerald-950 via-lime-950 to-slate-950",
      accent: "text-lime-400"
    }
  ];

  const current = screens[step - 1];

  const nextStep = () => {
    if (step < 3) {
      setStep(step + 1);
    } else {
      onFinish();
    }
  };

  return (
    <div className={`h-full w-full flex flex-col justify-between bg-gradient-to-b ${current.gradient} text-white p-6 relative overflow-hidden transition-all duration-700`}>
      {/* Skip Button */}
      <div className="flex justify-end pt-2">
        {step < 3 && (
          <button
            onClick={onFinish}
            className="text-sm font-medium text-slate-300 hover:text-white transition bg-white/10 px-3 py-1 rounded-full backdrop-blur-sm"
          >
            Skip
          </button>
        )}
      </div>

      {/* Main Content Area */}
      <div className="flex-1 flex flex-col justify-center items-center text-center my-6">
        <AnimatePresence mode="wait">
          <motion.div
            key={step}
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -30 }}
            transition={{ duration: 0.4, ease: "easeOut" }}
            className="flex flex-col items-center max-w-sm"
          >
            {/* Visual Icon Halo */}
            <div className="mb-8 relative flex items-center justify-center">
              <div className="absolute inset-0 bg-white/5 rounded-full w-28 h-28 animate-pulse blur-xl" />
              <div className="bg-white/10 p-6 rounded-3xl border border-white/20 shadow-xl backdrop-blur-md">
                {current.icon}
              </div>
            </div>

            <span className="text-xs uppercase tracking-widest font-bold text-slate-400 mb-2">
              Step {step} of 3
            </span>
            <h2 className={`text-2xl sm:text-3xl font-extrabold tracking-tight leading-tight ${current.accent}`}>
              {current.title}
            </h2>
            <p className="text-md font-semibold text-slate-200 mt-3 px-2">
              {current.subtitle}
            </p>
            <p className="text-sm text-slate-400 mt-4 leading-relaxed px-4">
              {current.description}
            </p>
          </motion.div>
        </AnimatePresence>
      </div>

      {/* Footer controls */}
      <div className="pb-8 flex flex-col items-center">
        {/* Step Indicator Bullets */}
        <div className="flex gap-2 mb-8">
          {screens.map((s) => (
            <div
              key={s.id}
              onClick={() => setStep(s.id)}
              className={`h-2 rounded-full cursor-pointer transition-all duration-300 ${
                step === s.id ? "w-8 bg-white" : "w-2 bg-white/30"
              }`}
            />
          ))}
        </div>

        {/* Action Button */}
        <motion.button
          whileTap={{ scale: 0.95 }}
          onClick={nextStep}
          className={`w-full max-w-xs py-4 rounded-2xl font-bold flex items-center justify-center gap-2 shadow-lg hover:shadow-xl transition-all duration-300 ${
            step === 3 
              ? "bg-emerald-500 hover:bg-emerald-400 text-slate-950" 
              : "bg-white/20 hover:bg-white/30 text-white border border-white/20"
          }`}
        >
          {step === 3 ? (
            <>
              Let's Start <Play className="w-5 h-5 fill-slate-950 stroke-slate-950" />
            </>
          ) : (
            <>
              Continue <ChevronRight className="w-5 h-5" />
            </>
          )}
        </motion.button>
      </div>
    </div>
  );
}
