import { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Sparkles, Play, CheckCircle2, RefreshCw, ChevronRight, Dumbbell, MapPin, Clock, Trophy, ChevronDown, ChevronUp } from "lucide-react";
import { UserProfile, WorkoutPlan, WorkoutExercise } from "../types";

interface WorkoutViewProps {
  profile: UserProfile;
  workoutPlan: WorkoutPlan;
  onSaveWorkout: (plan: WorkoutPlan) => void;
}

export default function WorkoutView({ profile, workoutPlan, onSaveWorkout }: WorkoutViewProps) {
  // Generator options
  const [goal, setGoal] = useState(profile.goal);
  const [location, setLocation] = useState<"Home" | "Gym">("Gym");
  const [equipment, setEquipment] = useState("Full Gym Equipment");
  const [duration, setDuration] = useState(45);
  const [level, setLevel] = useState(profile.fitnessLevel);

  const [isLoading, setIsLoading] = useState(false);
  const [completedExercises, setCompletedExercises] = useState<string[]>([]);
  const [errorMsg, setErrorMsg] = useState("");
  const [expandedSection, setExpandedSection] = useState<"warmup" | "main" | "cooldown" | "weekly">("main");

  // Handle Workout Plan Generation from backend
  const handleGenerate = async () => {
    setIsLoading(true);
    setErrorMsg("");
    setCompletedExercises([]);

    try {
      const response = await fetch("/api/generate-workout", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ goal, location, equipment, duration, level })
      });

      if (!response.ok) {
        throw new Error("Server responded with error status");
      }

      const data: WorkoutPlan = await response.json();
      data.generatedAt = new Date().toISOString();
      onSaveWorkout(data);
    } catch (error: any) {
      console.error("Error generating workout:", error);
      setErrorMsg("Failed to communicate with AI Coach server. Using offline safe backup plan.");
    } finally {
      setIsLoading(false);
    }
  };

  const toggleExerciseComplete = (exercise: string) => {
    if (completedExercises.includes(exercise)) {
      setCompletedExercises(completedExercises.filter(e => e !== exercise));
    } else {
      setCompletedExercises([...completedExercises, exercise]);
    }
  };

  const toggleSection = (section: any) => {
    setExpandedSection(expandedSection === section ? null : section);
  };

  return (
    <div className="h-full w-full overflow-y-auto bg-slate-950 p-4 space-y-4 pb-24 text-slate-100">
      
      {/* Title */}
      <div className="flex justify-between items-center bg-slate-900/60 p-4 rounded-3xl border border-slate-800/80">
        <div>
          <h2 className="text-xl font-bold tracking-tight text-white">AI Workout Coach</h2>
          <p className="text-xs text-slate-400">Tailored training sessions generated by AI</p>
        </div>
        <Dumbbell className="w-8 h-8 text-emerald-400" />
      </div>

      <AnimatePresence mode="wait">
        {isLoading ? (
          /* Loading skeleton */
          <motion.div
            key="loading"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="bg-slate-900 border border-slate-800 rounded-3xl p-6 flex flex-col items-center justify-center text-center space-y-6 py-12"
          >
            <div className="relative">
              <div className="w-16 h-16 rounded-full border-4 border-emerald-500/20 border-t-emerald-500 animate-spin" />
              <Dumbbell className="w-6 h-6 text-emerald-400 absolute top-5 left-5 animate-pulse" />
            </div>
            <div className="space-y-2">
              <h3 className="text-md font-bold text-slate-200">Analyzing Your Anatomy</h3>
              <p className="text-xs text-slate-500 max-w-xs leading-relaxed">
                Consulting biomechanical models and adjusting reps, sets, and locations to design the ultimate routine...
              </p>
            </div>
            <div className="w-full max-w-xs space-y-2.5 pt-4">
              <div className="h-4 bg-slate-800 rounded-xl animate-pulse" />
              <div className="h-10 bg-slate-800 rounded-xl animate-pulse" />
              <div className="h-20 bg-slate-800 rounded-xl animate-pulse" />
            </div>
          </motion.div>
        ) : (
          <motion.div
            key="form-and-results"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="space-y-4"
          >
            {/* Generation Form */}
            <div className="bg-slate-900 border border-slate-800 rounded-3xl p-4 space-y-3">
              <span className="text-xs font-bold text-slate-400 uppercase tracking-wider block mb-1">Workout Configurations</span>

              <div className="grid grid-cols-2 gap-3 text-xs">
                {/* Location select */}
                <div>
                  <label className="text-slate-500 font-semibold flex items-center gap-1 mb-1">
                    <MapPin className="w-3.5 h-3.5 text-emerald-400" /> Location
                  </label>
                  <select
                    value={location}
                    onChange={(e) => setLocation(e.target.value as any)}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl p-2.5 text-slate-200 focus:outline-none"
                  >
                    <option value="Gym">Commercial Gym</option>
                    <option value="Home">Home Workout</option>
                  </select>
                </div>

                {/* Duration select */}
                <div>
                  <label className="text-slate-500 font-semibold flex items-center gap-1 mb-1">
                    <Clock className="w-3.5 h-3.5 text-emerald-400" /> Duration
                  </label>
                  <select
                    value={duration}
                    onChange={(e) => setDuration(parseInt(e.target.value))}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl p-2.5 text-slate-200 focus:outline-none"
                  >
                    <option value={20}>20 Minutes</option>
                    <option value={30}>30 Minutes</option>
                    <option value={45}>45 Minutes</option>
                    <option value={60}>60 Minutes</option>
                    <option value={90}>90 Minutes</option>
                  </select>
                </div>
              </div>

              {/* Equipment field */}
              <div className="text-xs">
                <label className="text-slate-500 font-semibold block mb-1">Equipment Available</label>
                <input
                  type="text"
                  value={equipment}
                  onChange={(e) => setEquipment(e.target.value)}
                  placeholder="e.g. Dumbbells, resistance bands, pullup bar..."
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl p-2.5 text-slate-200 focus:outline-none"
                />
              </div>

              <div className="grid grid-cols-2 gap-3 text-xs">
                {/* Level select */}
                <div>
                  <label className="text-slate-500 font-semibold block mb-1">Training Level</label>
                  <select
                    value={level}
                    onChange={(e) => setLevel(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl p-2.5 text-slate-200 focus:outline-none"
                  >
                    <option value="Beginner">Beginner</option>
                    <option value="Intermediate">Intermediate</option>
                    <option value="Advanced">Advanced</option>
                  </select>
                </div>

                {/* Goal select */}
                <div>
                  <label className="text-slate-500 font-semibold block mb-1">Fitness Goal</label>
                  <select
                    value={goal}
                    onChange={(e) => setGoal(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl p-2.5 text-slate-200 focus:outline-none"
                  >
                    <option value="Lose Fat">Lose Fat</option>
                    <option value="Gain Muscle">Gain Muscle</option>
                    <option value="Maintain Weight">Maintain Weight</option>
                    <option value="Improve Endurance">Improve Endurance</option>
                  </select>
                </div>
              </div>

              {errorMsg && (
                <p className="text-xxs text-amber-400 bg-amber-950/20 border border-amber-900/30 p-2.5 rounded-xl">
                  {errorMsg}
                </p>
              )}

              <button
                onClick={handleGenerate}
                className="w-full bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold py-3 rounded-2xl flex items-center justify-center gap-2 shadow-lg shadow-emerald-500/10 transition"
              >
                <Sparkles className="w-4 h-4 fill-slate-950" /> Generate AI Workout Plan
              </button>
            </div>

            {/* Generated Plan Output */}
            <div className="bg-slate-900 border border-slate-800 rounded-3xl overflow-hidden shadow-lg">
              
              {/* Header Info */}
              <div className="p-4 bg-gradient-to-r from-emerald-950/20 to-slate-900 border-b border-slate-800">
                <span className="text-xxs uppercase tracking-wider text-emerald-400 font-bold">Active Training Plan</span>
                <h3 className="text-md font-bold text-white mt-1">{workoutPlan.title}</h3>
                
                <div className="flex gap-4 mt-2.5 text-xxs text-slate-400">
                  <span>Duration: <strong className="text-slate-200">{workoutPlan.duration} mins</strong></span>
                  <span>Est. Calories: <strong className="text-slate-200">{workoutPlan.estimatedCalories} kcal</strong></span>
                </div>
              </div>

              {/* Exercise Sections */}
              <div className="p-3 space-y-2">

                {/* Section 1: Warm-up */}
                <div className="bg-slate-950/40 rounded-2xl border border-slate-800/40">
                  <button
                    onClick={() => toggleSection("warmup")}
                    className="w-full flex justify-between items-center p-3 text-xs font-bold text-slate-300"
                  >
                    <span className="flex items-center gap-1.5">
                      <Trophy className="w-4 h-4 text-emerald-400" /> Warm-up Routine ({workoutPlan.warmup.length} drills)
                    </span>
                    {expandedSection === "warmup" ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                  </button>

                  {expandedSection === "warmup" && (
                    <div className="p-3 pt-0 space-y-2 border-t border-slate-800/20 text-xs">
                      {workoutPlan.warmup.map((ex, idx) => (
                        <div key={idx} className="flex gap-3 bg-slate-900/60 p-2.5 rounded-xl">
                          <button
                            onClick={() => toggleExerciseComplete(ex.exercise)}
                            className="focus:outline-none pt-0.5"
                          >
                            <CheckCircle2 className={`w-4 h-4 ${completedExercises.includes(ex.exercise) ? "text-emerald-400 fill-emerald-500/10" : "text-slate-600"}`} />
                          </button>
                          <div className="flex-1">
                            <div className="flex justify-between font-bold">
                              <span className={completedExercises.includes(ex.exercise) ? "line-through text-slate-500" : "text-slate-200"}>{ex.exercise}</span>
                              <span className="text-emerald-400 text-xxs bg-emerald-500/10 px-1.5 py-0.5 rounded">{ex.duration}</span>
                            </div>
                            <p className="text-xxs text-slate-400 mt-1">{ex.instructions}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                {/* Section 2: Main Exercises */}
                <div className="bg-slate-950/40 rounded-2xl border border-slate-800/40">
                  <button
                    onClick={() => toggleSection("main")}
                    className="w-full flex justify-between items-center p-3 text-xs font-bold text-slate-300"
                  >
                    <span className="flex items-center gap-1.5">
                      <Dumbbell className="w-4 h-4 text-emerald-400" /> Primary Workout Sets ({workoutPlan.mainWorkout.length} lifts)
                    </span>
                    {expandedSection === "main" ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                  </button>

                  {expandedSection === "main" && (
                    <div className="p-3 pt-0 space-y-2.5 border-t border-slate-800/20 text-xs">
                      {workoutPlan.mainWorkout.map((ex, idx) => (
                        <div key={idx} className="flex gap-3 bg-slate-900/60 p-2.5 rounded-xl">
                          <button
                            onClick={() => toggleExerciseComplete(ex.exercise)}
                            className="focus:outline-none pt-0.5"
                          >
                            <CheckCircle2 className={`w-4.5 h-4.5 ${completedExercises.includes(ex.exercise) ? "text-emerald-400 fill-emerald-500/10" : "text-slate-600"}`} />
                          </button>
                          <div className="flex-1">
                            <div className="flex justify-between font-bold flex-wrap gap-1">
                              <span className={completedExercises.includes(ex.exercise) ? "line-through text-slate-500" : "text-slate-200"}>{ex.exercise}</span>
                              <div className="flex gap-1 text-xxs">
                                <span className="text-slate-400 bg-slate-800 px-1.5 py-0.5 rounded">{ex.sets} Sets</span>
                                <span className="text-slate-400 bg-slate-800 px-1.5 py-0.5 rounded">{ex.reps} Reps</span>
                                {ex.rest && <span className="text-slate-400 bg-slate-800 px-1.5 py-0.5 rounded">Rest {ex.rest}</span>}
                              </div>
                            </div>
                            <p className="text-xxs text-slate-400 mt-1">{ex.instructions}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                {/* Section 3: Cool-down */}
                <div className="bg-slate-950/40 rounded-2xl border border-slate-800/40">
                  <button
                    onClick={() => toggleSection("cooldown")}
                    className="w-full flex justify-between items-center p-3 text-xs font-bold text-slate-300"
                  >
                    <span className="flex items-center gap-1.5">
                      <Play className="w-4 h-4 text-emerald-400 rotate-90" /> Cool-down stretches
                    </span>
                    {expandedSection === "cooldown" ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                  </button>

                  {expandedSection === "cooldown" && (
                    <div className="p-3 pt-0 space-y-2 border-t border-slate-800/20 text-xs">
                      {workoutPlan.cooldown.map((ex, idx) => (
                        <div key={idx} className="flex gap-3 bg-slate-900/60 p-2.5 rounded-xl">
                          <button
                            onClick={() => toggleExerciseComplete(ex.exercise)}
                            className="focus:outline-none pt-0.5"
                          >
                            <CheckCircle2 className={`w-4 h-4 ${completedExercises.includes(ex.exercise) ? "text-emerald-400 fill-emerald-500/10" : "text-slate-600"}`} />
                          </button>
                          <div className="flex-1">
                            <div className="flex justify-between font-bold">
                              <span className={completedExercises.includes(ex.exercise) ? "line-through text-slate-500" : "text-slate-200"}>{ex.exercise}</span>
                              <span className="text-emerald-400 text-xxs bg-emerald-500/10 px-1.5 py-0.5 rounded">{ex.duration}</span>
                            </div>
                            <p className="text-xxs text-slate-400 mt-1">{ex.instructions}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                {/* Section 4: Weekly Plan split */}
                <div className="bg-slate-950/40 rounded-2xl border border-slate-800/40">
                  <button
                    onClick={() => toggleSection("weekly")}
                    className="w-full flex justify-between items-center p-3 text-xs font-bold text-slate-300"
                  >
                    <span className="flex items-center gap-1.5">
                      <Sparkles className="w-4 h-4 text-emerald-400" /> Weekly Training Split
                    </span>
                    {expandedSection === "weekly" ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                  </button>

                  {expandedSection === "weekly" && (
                    <div className="p-3 pt-0 space-y-2 border-t border-slate-800/20 text-xs">
                      <p className="text-xxs text-slate-500 mb-2">Weekly progression split recommended by FitGen Coach AI:</p>
                      {workoutPlan.weeklyPlan.map((p, idx) => (
                        <div key={idx} className="flex justify-between items-center bg-slate-900/60 p-2.5 rounded-xl">
                          <div>
                            <span className="font-extrabold text-slate-200 block">{p.day}</span>
                            <span className="text-xxs text-slate-400">{p.workoutType} ({p.focus})</span>
                          </div>
                          <span className="text-xxs bg-slate-800 px-2 py-1 rounded text-slate-300 font-bold">{p.duration} mins</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

              </div>

              {/* Progress completed indicator */}
              <div className="p-4 bg-slate-950/80 border-t border-slate-800 flex justify-between items-center text-xs">
                <span>Completed: <strong>{completedExercises.length}</strong> of <strong>{workoutPlan.warmup.length + workoutPlan.mainWorkout.length + workoutPlan.cooldown.length}</strong></span>
                <div className="flex-1 max-w-[120px] bg-slate-800 h-2 rounded-full overflow-hidden mx-3">
                  <div 
                    className="bg-emerald-500 h-full rounded-full transition-all"
                    style={{ width: `${((completedExercises.length) / (workoutPlan.warmup.length + workoutPlan.mainWorkout.length + workoutPlan.cooldown.length)) * 100 || 0}%` }}
                  />
                </div>
                <span className="text-emerald-400 font-bold">{Math.round(((completedExercises.length) / (workoutPlan.warmup.length + workoutPlan.mainWorkout.length + workoutPlan.cooldown.length)) * 100) || 0}%</span>
              </div>

            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
